module.exports = {
  plugins: ["testing-library"],
  rules: {
    "testing-library/await-async-query": "error",
    "testing-library/await-async-utils": "error",
    "testing-library/await-fire-event": "warn",
    "testing-library/consistent-data-testid": "warn",
    "testing-library/no-await-sync-events": "warn",
    "testing-library/no-await-sync-query": "error",
    "testing-library/no-container": "error",
    "testing-library/no-debugging-utils": "error",
    "testing-library/no-dom-import": "error",
    "testing-library/no-global-regexp-flag-in-query": "warn",
    "testing-library/no-manual-cleanup": "warn",
    "testing-library/no-node-access": "error",
    "testing-library/no-promise-in-fire-event": "error",
    "testing-library/no-render-in-setup": "error",
    "testing-library/no-unnecessary-act": "error",
    "testing-library/no-wait-for-empty-callback": "error",
    "testing-library/no-wait-for-multiple-assertions": "error",
    "testing-library/no-wait-for-side-effects": "error",
    "testing-library/no-wait-for-snapshot": "error",
    "testing-library/prefer-explicit-assert": "warn",
    "testing-library/prefer-find-by": "error",
    "testing-library/prefer-presence-queries": "error",
    "testing-library/prefer-query-by-disappearance": "error",
    "testing-library/prefer-screen-queries": "error",
    "testing-library/prefer-user-event": "warn",
    "testing-library/wait-for": "warn",
    "testing-library/render-result-naming-convention": "error",
  },
};
